server:
  port: 7777
  context-path: /ems
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ems
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: /
      prefix: .jsp
  http:
    encoding:
      charset: UTF-8
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity